### ISSUE TITLE
官方启用CSP规则之后无法使用

### ISSUE THREAD

**Issue by zglhappy** [DoooReyn/WxRead-WebAutoReader#5]
尊敬的开发者：
您好，
今天登陆微信读书再使用，发现已经无法自动阅读。
去知乎看了一下，也有小伙伴遇到同样问题，推测可能失效。
您是否便于解决？如有打扰，非常抱歉！
感谢您的耐心阅读。

**Comment by androidfans** [comment]
VM159:1 Refused to create a worker from 'blob:https://weread.qq.com/4b74b5a8-1e66-4892-8aab-2235e9675345' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' 'nonce-FFE0DF8E008967ACCC09FA33F50CC7A2' https://weread-1258476243.file.myqcloud.com/ 'report-sample'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by DoooReyn** [comment]
从目前情况来看，是官方启用了CSP规则，因此使用Worker作为定时器已不可取。正在寻求解决方案。

**Comment by androidfans** [comment]
用 selenium 实现了一个。  部署到腾讯云上执行了

**Comment by DoooReyn** [comment]
> 用 selenium 实现了一个。 部署到腾讯云上执行了

可以分享一下。

**Comment by DoooReyn** [comment]
目前已修复，各位可以更新测试看看。

**Comment by zglhappy** [comment]
非常感谢您的更新~
现在已经可以正常使用。
祝您万事胜意~
